spring:
  application:
    name: peach-service
say:
  ribbon:
    listOfServers: http://localhost:8091,http://localhost:8092
ribbon:
  eureka:
    enabled: false
rocketmq:
  name-server: 112.124.109.237:9876
  producer:
    group: producer-group-1
  consumer:
    group: consumer-group-1